const routes = {
  '/': 'Home',
  '/dashboard': 'Dashboard',
  '/components': 'Components',
  '/charts': 'Charts',
  '/components/buttons': 'Buttons',
  '/components/social-buttons': 'Social Buttons',
  '/components/cards': 'Cards',
  '/components/forms': 'Forms',
  '/components/modals': 'Modals',
  '/components/switches': 'Switches',
  '/components/tables': 'Tables',
  '/components/tabs': 'Tabs',
  '/forms': 'Forms',
  '/forms/basic-forms': 'Basic Forms',
  '/forms/advanced-forms': 'Advanced Forms',
  '/icons': 'Icons',
  '/icons/font-awesome': 'Font Awesome',
  '/icons/glyphicons': 'Glyphicons',
  '/icons/glyphicons-filetypes': 'Glyphicons Filetypes',
  '/icons/glyphicons-social': 'Glyphicons Social',
  '/icons/simple-line-icons': 'Simple Line Icons',
  '/plugins': 'Plugins',
  '/plugins/loading-buttons': 'Loading Buttons',
  '/plugins/spinners': 'Spinners',
  '/widgets': 'Widgets'
};
export default routes;
